<?php $this->headLink()->appendStylesheet('/css/blog/index/index.css'); ?>

<?php if (!empty($this->paginator)) : ?>
    <div id="blog-posts">
        <?php foreach ($this->paginator as $post) : ?>
            <?php /** @var \Article\Entity\Post $post */ ?>
            <?php
                $date = new DateTime($post->getCreated());
                $postedAt = $date->format('Y-m-d H:i');
            ?>

            <div class="blog-post">
                <h2>

                        <?php echo $post->getCategory()->getName() . ': ' . $this->escapeHtml($post->getTitle()); ?>

                </h2>

                <div class="posted-at">
                    <?php echo sprintf($this->translate('Posted on %s in the %s category'), $postedAt, $this->escapeHtml($post->getCategory()->getName())); ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php else : ?>
    <p><?php echo $this->translate('There are currently no articles.'); ?></p>
<?php endif; ?>